% plotting phase trajectories
hold on
grid on
xlabel('y', 'FontSize', 16)
ylabel('dy', 'FontSize', 16)
ax = gca;
ax.FontSize = 16; 
plot(out.y1.Data, out.dy1.Data, ...
    out.y2.Data, out.dy2.Data, ...
    out.y3.Data, out.dy3.Data, ...
    out.y4.Data, out.dy4.Data, ...
    out.y5.Data, out.dy5.Data, ...
    out.y6.Data, out.dy6.Data, LineWidth=2)
title(['roots: z_1 = ', num2str(z1), ', z_2 = ', num2str(z2)])